const customFileHeader = [
	"Do not edit directly — this is auto generated by style-dictionary",
	"Updates are made via ./tokens/*.json",
];

var Color = require("tinycolor2");

module.exports = {
	source: ["./tokens/**/*.json"],
	hooks: {
		// Style Dictionary v4+: custom transforms live under hooks.transforms,
		// with `matcher` renamed to `filter` and `transformer` to `transform`.
		transforms: {
			boxShadowTransformer: {
				type: "value",
				filter: (token) => token.path.includes("box-shadow"),
				transform: (token) => token.value,
			},
			hexToHsl: {
				type: "value",
				filter: (token) =>
					/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(token.value),
				transform: (token) => {
					return Color(token.value).toHslString();
				},
			},
			pxToRem: {
				type: "value",
				// filter: token => /\d*\.?\d*px/i.test(token.value) ,
				filter: (token) =>
					/\d*\.?\d*px/i.test(token.value) && !token.path.includes("box-shadow"),
				transform: (token) => {
					const floatVal = parseFloat(token.value);

					if (floatVal === 0) {
						return "0";
					}

					return `${floatVal / 16}rem`;
				},
			},
			stripPxUnit: {
				type: "value",
				filter: (token) =>
					typeof token.value === "string" &&
					token.value.endsWith("px") &&
					token.path.includes("breakpoint"), // only for breakpoints
				transform: (token) => parseInt(token.value.replace("px", ""), 10),
			},
		},
		// v4+: file headers are registered hooks, referenced by name below.
		fileHeaders: {
			customFileHeader: () => customFileHeader,
		},
	},
	platforms: {
		scss: {
			buildPath: "styles/",
			transforms: [
				"attribute/cti",
				"name/kebab",
				"time/seconds",
				"html/icon",
				"size/rem",
				"color/css",
				"boxShadowTransformer",
				"pxToRem",
				"hexToHsl",
			],
			files: [
				{
					destination: "_css-variables.css",
					format: "css/variables",
					options: {
						fileHeader: "customFileHeader",
						outputReferences: true,
					},
				},
				{
					destination: "_base-variables.scss",
					format: "scss/variables",
					options: {
						fileHeader: "customFileHeader",
						outputReferences: true,
					},
				},
			],
		},
		js: {
			buildPath: "./styles/",
			transforms: [
				"attribute/cti",
				"name/pascal",
				"size/rem",
				"color/hex",
				"boxShadowTransformer",
				"hexToHsl",
				"stripPxUnit",
			],
			files: [
				{
					destination: "variables.js",
					format: "javascript/es6",
					options: {
						fileHeader: "customFileHeader",
						outputReferences: true,
					},
				},
			],
		},
	},
};
